services:
  web:
    build:
      context: ./src
    container_name: roamance_web
    user: root
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html
    depends_on:
      - tailscale-nginx
    restart: unless-stopped

  tailscale-nginx:
    image: tailscale/tailscale:latest
    hostname: tailscale-nginx
    environment:
      - TS_AUTHKEY=tskey-auth-k2ZCJwdeGH11CNTRL-GawYZgfCPESGpXz2pK6gDSAY4yGCoYf1
      - TS_STATE_DIR=/var/lib/tailscale
      - TS_USERSPACE=false
      - TS_AUTH_ONCE=true
    volumes:
      - ./tailscale-nginx/state:/var/lib/tailscale
    devices:
      - /dev/net/tun:/dev/net/tun
    cap_add:
      - net_admin
    restart: unless-stopped

  nginx:
    image: nginx
    depends_on:
      - tailscale-nginx
    network_mode: service:tailscale-nginx
    volumes:
      - ./src:/usr/share/nginx/html

volumes:
  db_data:
